# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('pub_date', models.DateField(blank=True)),
                ('pdf_file', models.FileField(upload_to='papers/')),
            ],
        ),
    ]
