# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=150)),
                ('venue_type', models.CharField(choices=[('Journal', 'Journal'), ('Conference', 'Conference'), ('Book Chapter', 'Book Chapter'), ('Workshop', 'Workshop'), ('Poster', 'Poster'), ('Thesis', 'Thesis'), ('Misc.', 'Misc.')], default='Misc.', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='papers/'),
        ),
    ]
