# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubs', '0002_auto_20160704_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pubs.Venue'),
        ),
    ]
