# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('PHD', 'PhD'), ('MS', 'MS'), ('BS', 'BS')], default='STUDENT', max_length=10)),
                ('degree', models.CharField(choices=[('PHD', 'PhD'), ('MS', 'MS'), ('BS', 'BS')], default='BS', max_length=10)),
                ('website', models.URLField(blank=True)),
                ('has_graduated', models.BooleanField(default=False)),
                ('postgrad_job', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
